#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTrungTamGiaSu
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLGIASU")]
	public partial class QL_TTGiaSuaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTHOIGIAN(THOIGIAN instance);
    partial void UpdateTHOIGIAN(THOIGIAN instance);
    partial void DeleteTHOIGIAN(THOIGIAN instance);
    partial void InsertCHITIETG(CHITIETG instance);
    partial void UpdateCHITIETG(CHITIETG instance);
    partial void DeleteCHITIETG(CHITIETG instance);
    partial void InsertCHITIETLOPTRUNGTAM(CHITIETLOPTRUNGTAM instance);
    partial void UpdateCHITIETLOPTRUNGTAM(CHITIETLOPTRUNGTAM instance);
    partial void DeleteCHITIETLOPTRUNGTAM(CHITIETLOPTRUNGTAM instance);
    partial void InsertDANHSACHHEN(DANHSACHHEN instance);
    partial void UpdateDANHSACHHEN(DANHSACHHEN instance);
    partial void DeleteDANHSACHHEN(DANHSACHHEN instance);
    partial void InsertGIASU(GIASU instance);
    partial void UpdateGIASU(GIASU instance);
    partial void DeleteGIASU(GIASU instance);
    partial void InsertHOCVIEN(HOCVIEN instance);
    partial void UpdateHOCVIEN(HOCVIEN instance);
    partial void DeleteHOCVIEN(HOCVIEN instance);
    partial void InsertKHUVUC(KHUVUC instance);
    partial void UpdateKHUVUC(KHUVUC instance);
    partial void DeleteKHUVUC(KHUVUC instance);
    partial void InsertLOP(LOP instance);
    partial void UpdateLOP(LOP instance);
    partial void DeleteLOP(LOP instance);
    partial void InsertLOPTRUNGTAM(LOPTRUNGTAM instance);
    partial void UpdateLOPTRUNGTAM(LOPTRUNGTAM instance);
    partial void DeleteLOPTRUNGTAM(LOPTRUNGTAM instance);
    partial void InsertMON(MON instance);
    partial void UpdateMON(MON instance);
    partial void DeleteMON(MON instance);
    partial void InsertNHANVIEN(NHANVIEN instance);
    partial void UpdateNHANVIEN(NHANVIEN instance);
    partial void DeleteNHANVIEN(NHANVIEN instance);
    partial void InsertPHUHUYNH(PHUHUYNH instance);
    partial void UpdatePHUHUYNH(PHUHUYNH instance);
    partial void DeletePHUHUYNH(PHUHUYNH instance);
    partial void InsertTAIKHOAN(TAIKHOAN instance);
    partial void UpdateTAIKHOAN(TAIKHOAN instance);
    partial void DeleteTAIKHOAN(TAIKHOAN instance);
    #endregion
		
		public QL_TTGiaSuaDataContext() : 
				base(global::QuanLyTrungTamGiaSu.Properties.Settings.Default.QL_TrungTamConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QL_TTGiaSuaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QL_TTGiaSuaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QL_TTGiaSuaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QL_TTGiaSuaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<THOIGIAN> THOIGIANs
		{
			get
			{
				return this.GetTable<THOIGIAN>();
			}
		}
		
		public System.Data.Linq.Table<CHITIETG> CHITIETGs
		{
			get
			{
				return this.GetTable<CHITIETG>();
			}
		}
		
		public System.Data.Linq.Table<CHITIETLOPTRUNGTAM> CHITIETLOPTRUNGTAMs
		{
			get
			{
				return this.GetTable<CHITIETLOPTRUNGTAM>();
			}
		}
		
		public System.Data.Linq.Table<DANHSACHHEN> DANHSACHHENs
		{
			get
			{
				return this.GetTable<DANHSACHHEN>();
			}
		}
		
		public System.Data.Linq.Table<GIASU> GIASUs
		{
			get
			{
				return this.GetTable<GIASU>();
			}
		}
		
		public System.Data.Linq.Table<HOCVIEN> HOCVIENs
		{
			get
			{
				return this.GetTable<HOCVIEN>();
			}
		}
		
		public System.Data.Linq.Table<KHUVUC> KHUVUCs
		{
			get
			{
				return this.GetTable<KHUVUC>();
			}
		}
		
		public System.Data.Linq.Table<LOP> LOPs
		{
			get
			{
				return this.GetTable<LOP>();
			}
		}
		
		public System.Data.Linq.Table<LOPTRUNGTAM> LOPTRUNGTAMs
		{
			get
			{
				return this.GetTable<LOPTRUNGTAM>();
			}
		}
		
		public System.Data.Linq.Table<MON> MONs
		{
			get
			{
				return this.GetTable<MON>();
			}
		}
		
		public System.Data.Linq.Table<NHANVIEN> NHANVIENs
		{
			get
			{
				return this.GetTable<NHANVIEN>();
			}
		}
		
		public System.Data.Linq.Table<PHUHUYNH> PHUHUYNHs
		{
			get
			{
				return this.GetTable<PHUHUYNH>();
			}
		}
		
		public System.Data.Linq.Table<TAIKHOAN> TAIKHOANs
		{
			get
			{
				return this.GetTable<TAIKHOAN>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.THOIGIAN")]
	public partial class THOIGIAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MATG;
		
		private string _TENTG;
		
		private EntitySet<CHITIETG> _CHITIETGs;
		
		private EntitySet<LOPTRUNGTAM> _LOPTRUNGTAMs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMATGChanging(int value);
    partial void OnMATGChanged();
    partial void OnTENTGChanging(string value);
    partial void OnTENTGChanged();
    #endregion
		
		public THOIGIAN()
		{
			this._CHITIETGs = new EntitySet<CHITIETG>(new Action<CHITIETG>(this.attach_CHITIETGs), new Action<CHITIETG>(this.detach_CHITIETGs));
			this._LOPTRUNGTAMs = new EntitySet<LOPTRUNGTAM>(new Action<LOPTRUNGTAM>(this.attach_LOPTRUNGTAMs), new Action<LOPTRUNGTAM>(this.detach_LOPTRUNGTAMs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATG", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MATG
		{
			get
			{
				return this._MATG;
			}
			set
			{
				if ((this._MATG != value))
				{
					this.OnMATGChanging(value);
					this.SendPropertyChanging();
					this._MATG = value;
					this.SendPropertyChanged("MATG");
					this.OnMATGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENTG", DbType="NVarChar(100)")]
		public string TENTG
		{
			get
			{
				return this._TENTG;
			}
			set
			{
				if ((this._TENTG != value))
				{
					this.OnTENTGChanging(value);
					this.SendPropertyChanging();
					this._TENTG = value;
					this.SendPropertyChanged("TENTG");
					this.OnTENTGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THOIGIAN_CHITIETG", Storage="_CHITIETGs", ThisKey="MATG", OtherKey="MATG")]
		public EntitySet<CHITIETG> CHITIETGs
		{
			get
			{
				return this._CHITIETGs;
			}
			set
			{
				this._CHITIETGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THOIGIAN_LOPTRUNGTAM", Storage="_LOPTRUNGTAMs", ThisKey="MATG", OtherKey="MATG")]
		public EntitySet<LOPTRUNGTAM> LOPTRUNGTAMs
		{
			get
			{
				return this._LOPTRUNGTAMs;
			}
			set
			{
				this._LOPTRUNGTAMs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHITIETGs(CHITIETG entity)
		{
			this.SendPropertyChanging();
			entity.THOIGIAN = this;
		}
		
		private void detach_CHITIETGs(CHITIETG entity)
		{
			this.SendPropertyChanging();
			entity.THOIGIAN = null;
		}
		
		private void attach_LOPTRUNGTAMs(LOPTRUNGTAM entity)
		{
			this.SendPropertyChanging();
			entity.THOIGIAN = this;
		}
		
		private void detach_LOPTRUNGTAMs(LOPTRUNGTAM entity)
		{
			this.SendPropertyChanging();
			entity.THOIGIAN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHITIETGS")]
	public partial class CHITIETG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MAGS;
		
		private int _MAMON;
		
		private int _MALOP;
		
		private int _MAKV;
		
		private int _MATG;
		
		private string _YEUCAUKHAC;
		
		private EntityRef<THOIGIAN> _THOIGIAN;
		
		private EntityRef<GIASU> _GIASU;
		
		private EntityRef<KHUVUC> _KHUVUC;
		
		private EntityRef<LOP> _LOP;
		
		private EntityRef<MON> _MON;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAGSChanging(int value);
    partial void OnMAGSChanged();
    partial void OnMAMONChanging(int value);
    partial void OnMAMONChanged();
    partial void OnMALOPChanging(int value);
    partial void OnMALOPChanged();
    partial void OnMAKVChanging(int value);
    partial void OnMAKVChanged();
    partial void OnMATGChanging(int value);
    partial void OnMATGChanged();
    partial void OnYEUCAUKHACChanging(string value);
    partial void OnYEUCAUKHACChanged();
    #endregion
		
		public CHITIETG()
		{
			this._THOIGIAN = default(EntityRef<THOIGIAN>);
			this._GIASU = default(EntityRef<GIASU>);
			this._KHUVUC = default(EntityRef<KHUVUC>);
			this._LOP = default(EntityRef<LOP>);
			this._MON = default(EntityRef<MON>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAGS", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MAGS
		{
			get
			{
				return this._MAGS;
			}
			set
			{
				if ((this._MAGS != value))
				{
					if (this._GIASU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAGSChanging(value);
					this.SendPropertyChanging();
					this._MAGS = value;
					this.SendPropertyChanged("MAGS");
					this.OnMAGSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAMON", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MAMON
		{
			get
			{
				return this._MAMON;
			}
			set
			{
				if ((this._MAMON != value))
				{
					if (this._MON.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAMONChanging(value);
					this.SendPropertyChanging();
					this._MAMON = value;
					this.SendPropertyChanged("MAMON");
					this.OnMAMONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MALOP", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MALOP
		{
			get
			{
				return this._MALOP;
			}
			set
			{
				if ((this._MALOP != value))
				{
					if (this._LOP.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMALOPChanging(value);
					this.SendPropertyChanging();
					this._MALOP = value;
					this.SendPropertyChanged("MALOP");
					this.OnMALOPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAKV", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MAKV
		{
			get
			{
				return this._MAKV;
			}
			set
			{
				if ((this._MAKV != value))
				{
					if (this._KHUVUC.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAKVChanging(value);
					this.SendPropertyChanging();
					this._MAKV = value;
					this.SendPropertyChanged("MAKV");
					this.OnMAKVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATG", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MATG
		{
			get
			{
				return this._MATG;
			}
			set
			{
				if ((this._MATG != value))
				{
					if (this._THOIGIAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMATGChanging(value);
					this.SendPropertyChanging();
					this._MATG = value;
					this.SendPropertyChanged("MATG");
					this.OnMATGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YEUCAUKHAC", DbType="NVarChar(1000)")]
		public string YEUCAUKHAC
		{
			get
			{
				return this._YEUCAUKHAC;
			}
			set
			{
				if ((this._YEUCAUKHAC != value))
				{
					this.OnYEUCAUKHACChanging(value);
					this.SendPropertyChanging();
					this._YEUCAUKHAC = value;
					this.SendPropertyChanged("YEUCAUKHAC");
					this.OnYEUCAUKHACChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THOIGIAN_CHITIETG", Storage="_THOIGIAN", ThisKey="MATG", OtherKey="MATG", IsForeignKey=true)]
		public THOIGIAN THOIGIAN
		{
			get
			{
				return this._THOIGIAN.Entity;
			}
			set
			{
				THOIGIAN previousValue = this._THOIGIAN.Entity;
				if (((previousValue != value) 
							|| (this._THOIGIAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._THOIGIAN.Entity = null;
						previousValue.CHITIETGs.Remove(this);
					}
					this._THOIGIAN.Entity = value;
					if ((value != null))
					{
						value.CHITIETGs.Add(this);
						this._MATG = value.MATG;
					}
					else
					{
						this._MATG = default(int);
					}
					this.SendPropertyChanged("THOIGIAN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GIASU_CHITIETG", Storage="_GIASU", ThisKey="MAGS", OtherKey="MAGS", IsForeignKey=true)]
		public GIASU GIASU
		{
			get
			{
				return this._GIASU.Entity;
			}
			set
			{
				GIASU previousValue = this._GIASU.Entity;
				if (((previousValue != value) 
							|| (this._GIASU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GIASU.Entity = null;
						previousValue.CHITIETGs.Remove(this);
					}
					this._GIASU.Entity = value;
					if ((value != null))
					{
						value.CHITIETGs.Add(this);
						this._MAGS = value.MAGS;
					}
					else
					{
						this._MAGS = default(int);
					}
					this.SendPropertyChanged("GIASU");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHUVUC_CHITIETG", Storage="_KHUVUC", ThisKey="MAKV", OtherKey="MAKV", IsForeignKey=true)]
		public KHUVUC KHUVUC
		{
			get
			{
				return this._KHUVUC.Entity;
			}
			set
			{
				KHUVUC previousValue = this._KHUVUC.Entity;
				if (((previousValue != value) 
							|| (this._KHUVUC.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHUVUC.Entity = null;
						previousValue.CHITIETGs.Remove(this);
					}
					this._KHUVUC.Entity = value;
					if ((value != null))
					{
						value.CHITIETGs.Add(this);
						this._MAKV = value.MAKV;
					}
					else
					{
						this._MAKV = default(int);
					}
					this.SendPropertyChanged("KHUVUC");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOP_CHITIETG", Storage="_LOP", ThisKey="MALOP", OtherKey="MALOP", IsForeignKey=true)]
		public LOP LOP
		{
			get
			{
				return this._LOP.Entity;
			}
			set
			{
				LOP previousValue = this._LOP.Entity;
				if (((previousValue != value) 
							|| (this._LOP.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOP.Entity = null;
						previousValue.CHITIETGs.Remove(this);
					}
					this._LOP.Entity = value;
					if ((value != null))
					{
						value.CHITIETGs.Add(this);
						this._MALOP = value.MALOP;
					}
					else
					{
						this._MALOP = default(int);
					}
					this.SendPropertyChanged("LOP");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MON_CHITIETG", Storage="_MON", ThisKey="MAMON", OtherKey="MAMON", IsForeignKey=true)]
		public MON MON
		{
			get
			{
				return this._MON.Entity;
			}
			set
			{
				MON previousValue = this._MON.Entity;
				if (((previousValue != value) 
							|| (this._MON.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MON.Entity = null;
						previousValue.CHITIETGs.Remove(this);
					}
					this._MON.Entity = value;
					if ((value != null))
					{
						value.CHITIETGs.Add(this);
						this._MAMON = value.MAMON;
					}
					else
					{
						this._MAMON = default(int);
					}
					this.SendPropertyChanged("MON");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHITIETLOPTRUNGTAM")]
	public partial class CHITIETLOPTRUNGTAM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MALOPTT;
		
		private int _MAGS;
		
		private System.Nullable<double> _MUCLUONG;
		
		private System.Nullable<double> _PHINHANLOP;
		
		private System.Nullable<System.DateTime> _NGAYNHANLOP;
		
		private System.Nullable<int> _MANV;
		
		private EntityRef<GIASU> _GIASU;
		
		private EntityRef<LOPTRUNGTAM> _LOPTRUNGTAM;
		
		private EntityRef<NHANVIEN> _NHANVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMALOPTTChanging(int value);
    partial void OnMALOPTTChanged();
    partial void OnMAGSChanging(int value);
    partial void OnMAGSChanged();
    partial void OnMUCLUONGChanging(System.Nullable<double> value);
    partial void OnMUCLUONGChanged();
    partial void OnPHINHANLOPChanging(System.Nullable<double> value);
    partial void OnPHINHANLOPChanged();
    partial void OnNGAYNHANLOPChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYNHANLOPChanged();
    partial void OnMANVChanging(System.Nullable<int> value);
    partial void OnMANVChanged();
    #endregion
		
		public CHITIETLOPTRUNGTAM()
		{
			this._GIASU = default(EntityRef<GIASU>);
			this._LOPTRUNGTAM = default(EntityRef<LOPTRUNGTAM>);
			this._NHANVIEN = default(EntityRef<NHANVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MALOPTT", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MALOPTT
		{
			get
			{
				return this._MALOPTT;
			}
			set
			{
				if ((this._MALOPTT != value))
				{
					if (this._LOPTRUNGTAM.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMALOPTTChanging(value);
					this.SendPropertyChanging();
					this._MALOPTT = value;
					this.SendPropertyChanged("MALOPTT");
					this.OnMALOPTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAGS", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MAGS
		{
			get
			{
				return this._MAGS;
			}
			set
			{
				if ((this._MAGS != value))
				{
					if (this._GIASU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAGSChanging(value);
					this.SendPropertyChanging();
					this._MAGS = value;
					this.SendPropertyChanged("MAGS");
					this.OnMAGSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MUCLUONG", DbType="Float")]
		public System.Nullable<double> MUCLUONG
		{
			get
			{
				return this._MUCLUONG;
			}
			set
			{
				if ((this._MUCLUONG != value))
				{
					this.OnMUCLUONGChanging(value);
					this.SendPropertyChanging();
					this._MUCLUONG = value;
					this.SendPropertyChanged("MUCLUONG");
					this.OnMUCLUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PHINHANLOP", DbType="Float")]
		public System.Nullable<double> PHINHANLOP
		{
			get
			{
				return this._PHINHANLOP;
			}
			set
			{
				if ((this._PHINHANLOP != value))
				{
					this.OnPHINHANLOPChanging(value);
					this.SendPropertyChanging();
					this._PHINHANLOP = value;
					this.SendPropertyChanged("PHINHANLOP");
					this.OnPHINHANLOPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYNHANLOP", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYNHANLOP
		{
			get
			{
				return this._NGAYNHANLOP;
			}
			set
			{
				if ((this._NGAYNHANLOP != value))
				{
					this.OnNGAYNHANLOPChanging(value);
					this.SendPropertyChanging();
					this._NGAYNHANLOP = value;
					this.SendPropertyChanged("NGAYNHANLOP");
					this.OnNGAYNHANLOPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANV", DbType="Int")]
		public System.Nullable<int> MANV
		{
			get
			{
				return this._MANV;
			}
			set
			{
				if ((this._MANV != value))
				{
					if (this._NHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANVChanging(value);
					this.SendPropertyChanging();
					this._MANV = value;
					this.SendPropertyChanged("MANV");
					this.OnMANVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GIASU_CHITIETLOPTRUNGTAM", Storage="_GIASU", ThisKey="MAGS", OtherKey="MAGS", IsForeignKey=true)]
		public GIASU GIASU
		{
			get
			{
				return this._GIASU.Entity;
			}
			set
			{
				GIASU previousValue = this._GIASU.Entity;
				if (((previousValue != value) 
							|| (this._GIASU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GIASU.Entity = null;
						previousValue.CHITIETLOPTRUNGTAMs.Remove(this);
					}
					this._GIASU.Entity = value;
					if ((value != null))
					{
						value.CHITIETLOPTRUNGTAMs.Add(this);
						this._MAGS = value.MAGS;
					}
					else
					{
						this._MAGS = default(int);
					}
					this.SendPropertyChanged("GIASU");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOPTRUNGTAM_CHITIETLOPTRUNGTAM", Storage="_LOPTRUNGTAM", ThisKey="MALOPTT", OtherKey="MALOPTT", IsForeignKey=true)]
		public LOPTRUNGTAM LOPTRUNGTAM
		{
			get
			{
				return this._LOPTRUNGTAM.Entity;
			}
			set
			{
				LOPTRUNGTAM previousValue = this._LOPTRUNGTAM.Entity;
				if (((previousValue != value) 
							|| (this._LOPTRUNGTAM.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOPTRUNGTAM.Entity = null;
						previousValue.CHITIETLOPTRUNGTAMs.Remove(this);
					}
					this._LOPTRUNGTAM.Entity = value;
					if ((value != null))
					{
						value.CHITIETLOPTRUNGTAMs.Add(this);
						this._MALOPTT = value.MALOPTT;
					}
					else
					{
						this._MALOPTT = default(int);
					}
					this.SendPropertyChanged("LOPTRUNGTAM");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_CHITIETLOPTRUNGTAM", Storage="_NHANVIEN", ThisKey="MANV", OtherKey="MANV", IsForeignKey=true)]
		public NHANVIEN NHANVIEN
		{
			get
			{
				return this._NHANVIEN.Entity;
			}
			set
			{
				NHANVIEN previousValue = this._NHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._NHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANVIEN.Entity = null;
						previousValue.CHITIETLOPTRUNGTAMs.Remove(this);
					}
					this._NHANVIEN.Entity = value;
					if ((value != null))
					{
						value.CHITIETLOPTRUNGTAMs.Add(this);
						this._MANV = value.MANV;
					}
					else
					{
						this._MANV = default(Nullable<int>);
					}
					this.SendPropertyChanged("NHANVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DANHSACHHEN")]
	public partial class DANHSACHHEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MAHEN;
		
		private System.Nullable<int> _MAHV;
		
		private System.Nullable<int> _MAGS;
		
		private System.Nullable<System.DateTime> _THOIGIANHEN;
		
		private string _KETQUA;
		
		private EntityRef<GIASU> _GIASU;
		
		private EntityRef<HOCVIEN> _HOCVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAHENChanging(int value);
    partial void OnMAHENChanged();
    partial void OnMAHVChanging(System.Nullable<int> value);
    partial void OnMAHVChanged();
    partial void OnMAGSChanging(System.Nullable<int> value);
    partial void OnMAGSChanged();
    partial void OnTHOIGIANHENChanging(System.Nullable<System.DateTime> value);
    partial void OnTHOIGIANHENChanged();
    partial void OnKETQUAChanging(string value);
    partial void OnKETQUAChanged();
    #endregion
		
		public DANHSACHHEN()
		{
			this._GIASU = default(EntityRef<GIASU>);
			this._HOCVIEN = default(EntityRef<HOCVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAHEN", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MAHEN
		{
			get
			{
				return this._MAHEN;
			}
			set
			{
				if ((this._MAHEN != value))
				{
					this.OnMAHENChanging(value);
					this.SendPropertyChanging();
					this._MAHEN = value;
					this.SendPropertyChanged("MAHEN");
					this.OnMAHENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAHV", DbType="Int")]
		public System.Nullable<int> MAHV
		{
			get
			{
				return this._MAHV;
			}
			set
			{
				if ((this._MAHV != value))
				{
					if (this._HOCVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAHVChanging(value);
					this.SendPropertyChanging();
					this._MAHV = value;
					this.SendPropertyChanged("MAHV");
					this.OnMAHVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAGS", DbType="Int")]
		public System.Nullable<int> MAGS
		{
			get
			{
				return this._MAGS;
			}
			set
			{
				if ((this._MAGS != value))
				{
					if (this._GIASU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAGSChanging(value);
					this.SendPropertyChanging();
					this._MAGS = value;
					this.SendPropertyChanged("MAGS");
					this.OnMAGSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THOIGIANHEN", DbType="Date")]
		public System.Nullable<System.DateTime> THOIGIANHEN
		{
			get
			{
				return this._THOIGIANHEN;
			}
			set
			{
				if ((this._THOIGIANHEN != value))
				{
					this.OnTHOIGIANHENChanging(value);
					this.SendPropertyChanging();
					this._THOIGIANHEN = value;
					this.SendPropertyChanged("THOIGIANHEN");
					this.OnTHOIGIANHENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KETQUA", DbType="NVarChar(10)")]
		public string KETQUA
		{
			get
			{
				return this._KETQUA;
			}
			set
			{
				if ((this._KETQUA != value))
				{
					this.OnKETQUAChanging(value);
					this.SendPropertyChanging();
					this._KETQUA = value;
					this.SendPropertyChanged("KETQUA");
					this.OnKETQUAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GIASU_DANHSACHHEN", Storage="_GIASU", ThisKey="MAGS", OtherKey="MAGS", IsForeignKey=true)]
		public GIASU GIASU
		{
			get
			{
				return this._GIASU.Entity;
			}
			set
			{
				GIASU previousValue = this._GIASU.Entity;
				if (((previousValue != value) 
							|| (this._GIASU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GIASU.Entity = null;
						previousValue.DANHSACHHENs.Remove(this);
					}
					this._GIASU.Entity = value;
					if ((value != null))
					{
						value.DANHSACHHENs.Add(this);
						this._MAGS = value.MAGS;
					}
					else
					{
						this._MAGS = default(Nullable<int>);
					}
					this.SendPropertyChanged("GIASU");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOCVIEN_DANHSACHHEN", Storage="_HOCVIEN", ThisKey="MAHV", OtherKey="MAHV", IsForeignKey=true)]
		public HOCVIEN HOCVIEN
		{
			get
			{
				return this._HOCVIEN.Entity;
			}
			set
			{
				HOCVIEN previousValue = this._HOCVIEN.Entity;
				if (((previousValue != value) 
							|| (this._HOCVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HOCVIEN.Entity = null;
						previousValue.DANHSACHHENs.Remove(this);
					}
					this._HOCVIEN.Entity = value;
					if ((value != null))
					{
						value.DANHSACHHENs.Add(this);
						this._MAHV = value.MAHV;
					}
					else
					{
						this._MAHV = default(Nullable<int>);
					}
					this.SendPropertyChanged("HOCVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GIASU")]
	public partial class GIASU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MAGS;
		
		private string _TENGS;
		
		private string _GIOITINH;
		
		private System.Nullable<System.DateTime> _NGAYSINH;
		
		private string _CCCD;
		
		private string _NGUYENQUAN;
		
		private string _DIACHI;
		
		private string _EMAIL;
		
		private string _DIENTHOAI;
		
		private string _TRUONG;
		
		private string _NGANHHOC;
		
		private System.Nullable<int> _NAMTOTNGHIEP;
		
		private string _NGHENGHIEP;
		
		private string _MONDANGDAY;
		
		private string _UUDIEM;
		
		private System.Nullable<int> _SOBUOIDAY;
		
		private System.Nullable<bool> _TRANGTHAI;
		
		private EntitySet<CHITIETG> _CHITIETGs;
		
		private EntitySet<CHITIETLOPTRUNGTAM> _CHITIETLOPTRUNGTAMs;
		
		private EntitySet<DANHSACHHEN> _DANHSACHHENs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAGSChanging(int value);
    partial void OnMAGSChanged();
    partial void OnTENGSChanging(string value);
    partial void OnTENGSChanged();
    partial void OnGIOITINHChanging(string value);
    partial void OnGIOITINHChanged();
    partial void OnNGAYSINHChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYSINHChanged();
    partial void OnCCCDChanging(string value);
    partial void OnCCCDChanged();
    partial void OnNGUYENQUANChanging(string value);
    partial void OnNGUYENQUANChanged();
    partial void OnDIACHIChanging(string value);
    partial void OnDIACHIChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    partial void OnDIENTHOAIChanging(string value);
    partial void OnDIENTHOAIChanged();
    partial void OnTRUONGChanging(string value);
    partial void OnTRUONGChanged();
    partial void OnNGANHHOCChanging(string value);
    partial void OnNGANHHOCChanged();
    partial void OnNAMTOTNGHIEPChanging(System.Nullable<int> value);
    partial void OnNAMTOTNGHIEPChanged();
    partial void OnNGHENGHIEPChanging(string value);
    partial void OnNGHENGHIEPChanged();
    partial void OnMONDANGDAYChanging(string value);
    partial void OnMONDANGDAYChanged();
    partial void OnUUDIEMChanging(string value);
    partial void OnUUDIEMChanged();
    partial void OnSOBUOIDAYChanging(System.Nullable<int> value);
    partial void OnSOBUOIDAYChanged();
    partial void OnTRANGTHAIChanging(System.Nullable<bool> value);
    partial void OnTRANGTHAIChanged();
    #endregion
		
		public GIASU()
		{
			this._CHITIETGs = new EntitySet<CHITIETG>(new Action<CHITIETG>(this.attach_CHITIETGs), new Action<CHITIETG>(this.detach_CHITIETGs));
			this._CHITIETLOPTRUNGTAMs = new EntitySet<CHITIETLOPTRUNGTAM>(new Action<CHITIETLOPTRUNGTAM>(this.attach_CHITIETLOPTRUNGTAMs), new Action<CHITIETLOPTRUNGTAM>(this.detach_CHITIETLOPTRUNGTAMs));
			this._DANHSACHHENs = new EntitySet<DANHSACHHEN>(new Action<DANHSACHHEN>(this.attach_DANHSACHHENs), new Action<DANHSACHHEN>(this.detach_DANHSACHHENs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAGS", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MAGS
		{
			get
			{
				return this._MAGS;
			}
			set
			{
				if ((this._MAGS != value))
				{
					this.OnMAGSChanging(value);
					this.SendPropertyChanging();
					this._MAGS = value;
					this.SendPropertyChanged("MAGS");
					this.OnMAGSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENGS", DbType="NVarChar(50)")]
		public string TENGS
		{
			get
			{
				return this._TENGS;
			}
			set
			{
				if ((this._TENGS != value))
				{
					this.OnTENGSChanging(value);
					this.SendPropertyChanging();
					this._TENGS = value;
					this.SendPropertyChanged("TENGS");
					this.OnTENGSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIOITINH", DbType="Char(10)")]
		public string GIOITINH
		{
			get
			{
				return this._GIOITINH;
			}
			set
			{
				if ((this._GIOITINH != value))
				{
					this.OnGIOITINHChanging(value);
					this.SendPropertyChanging();
					this._GIOITINH = value;
					this.SendPropertyChanged("GIOITINH");
					this.OnGIOITINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYSINH", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYSINH
		{
			get
			{
				return this._NGAYSINH;
			}
			set
			{
				if ((this._NGAYSINH != value))
				{
					this.OnNGAYSINHChanging(value);
					this.SendPropertyChanging();
					this._NGAYSINH = value;
					this.SendPropertyChanged("NGAYSINH");
					this.OnNGAYSINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CCCD", DbType="Char(12)")]
		public string CCCD
		{
			get
			{
				return this._CCCD;
			}
			set
			{
				if ((this._CCCD != value))
				{
					this.OnCCCDChanging(value);
					this.SendPropertyChanging();
					this._CCCD = value;
					this.SendPropertyChanged("CCCD");
					this.OnCCCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGUYENQUAN", DbType="NVarChar(100)")]
		public string NGUYENQUAN
		{
			get
			{
				return this._NGUYENQUAN;
			}
			set
			{
				if ((this._NGUYENQUAN != value))
				{
					this.OnNGUYENQUANChanging(value);
					this.SendPropertyChanging();
					this._NGUYENQUAN = value;
					this.SendPropertyChanged("NGUYENQUAN");
					this.OnNGUYENQUANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHI", DbType="NVarChar(100)")]
		public string DIACHI
		{
			get
			{
				return this._DIACHI;
			}
			set
			{
				if ((this._DIACHI != value))
				{
					this.OnDIACHIChanging(value);
					this.SendPropertyChanging();
					this._DIACHI = value;
					this.SendPropertyChanged("DIACHI");
					this.OnDIACHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="NVarChar(100)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIENTHOAI", DbType="Char(10)")]
		public string DIENTHOAI
		{
			get
			{
				return this._DIENTHOAI;
			}
			set
			{
				if ((this._DIENTHOAI != value))
				{
					this.OnDIENTHOAIChanging(value);
					this.SendPropertyChanging();
					this._DIENTHOAI = value;
					this.SendPropertyChanged("DIENTHOAI");
					this.OnDIENTHOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRUONG", DbType="NVarChar(100)")]
		public string TRUONG
		{
			get
			{
				return this._TRUONG;
			}
			set
			{
				if ((this._TRUONG != value))
				{
					this.OnTRUONGChanging(value);
					this.SendPropertyChanging();
					this._TRUONG = value;
					this.SendPropertyChanged("TRUONG");
					this.OnTRUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGANHHOC", DbType="NVarChar(100)")]
		public string NGANHHOC
		{
			get
			{
				return this._NGANHHOC;
			}
			set
			{
				if ((this._NGANHHOC != value))
				{
					this.OnNGANHHOCChanging(value);
					this.SendPropertyChanging();
					this._NGANHHOC = value;
					this.SendPropertyChanged("NGANHHOC");
					this.OnNGANHHOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAMTOTNGHIEP", DbType="Int")]
		public System.Nullable<int> NAMTOTNGHIEP
		{
			get
			{
				return this._NAMTOTNGHIEP;
			}
			set
			{
				if ((this._NAMTOTNGHIEP != value))
				{
					this.OnNAMTOTNGHIEPChanging(value);
					this.SendPropertyChanging();
					this._NAMTOTNGHIEP = value;
					this.SendPropertyChanged("NAMTOTNGHIEP");
					this.OnNAMTOTNGHIEPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGHENGHIEP", DbType="NVarChar(100)")]
		public string NGHENGHIEP
		{
			get
			{
				return this._NGHENGHIEP;
			}
			set
			{
				if ((this._NGHENGHIEP != value))
				{
					this.OnNGHENGHIEPChanging(value);
					this.SendPropertyChanging();
					this._NGHENGHIEP = value;
					this.SendPropertyChanged("NGHENGHIEP");
					this.OnNGHENGHIEPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MONDANGDAY", DbType="NVarChar(10)")]
		public string MONDANGDAY
		{
			get
			{
				return this._MONDANGDAY;
			}
			set
			{
				if ((this._MONDANGDAY != value))
				{
					this.OnMONDANGDAYChanging(value);
					this.SendPropertyChanging();
					this._MONDANGDAY = value;
					this.SendPropertyChanged("MONDANGDAY");
					this.OnMONDANGDAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UUDIEM", DbType="NVarChar(1000)")]
		public string UUDIEM
		{
			get
			{
				return this._UUDIEM;
			}
			set
			{
				if ((this._UUDIEM != value))
				{
					this.OnUUDIEMChanging(value);
					this.SendPropertyChanging();
					this._UUDIEM = value;
					this.SendPropertyChanged("UUDIEM");
					this.OnUUDIEMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOBUOIDAY", DbType="Int")]
		public System.Nullable<int> SOBUOIDAY
		{
			get
			{
				return this._SOBUOIDAY;
			}
			set
			{
				if ((this._SOBUOIDAY != value))
				{
					this.OnSOBUOIDAYChanging(value);
					this.SendPropertyChanging();
					this._SOBUOIDAY = value;
					this.SendPropertyChanged("SOBUOIDAY");
					this.OnSOBUOIDAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRANGTHAI", DbType="Bit")]
		public System.Nullable<bool> TRANGTHAI
		{
			get
			{
				return this._TRANGTHAI;
			}
			set
			{
				if ((this._TRANGTHAI != value))
				{
					this.OnTRANGTHAIChanging(value);
					this.SendPropertyChanging();
					this._TRANGTHAI = value;
					this.SendPropertyChanged("TRANGTHAI");
					this.OnTRANGTHAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GIASU_CHITIETG", Storage="_CHITIETGs", ThisKey="MAGS", OtherKey="MAGS")]
		public EntitySet<CHITIETG> CHITIETGs
		{
			get
			{
				return this._CHITIETGs;
			}
			set
			{
				this._CHITIETGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GIASU_CHITIETLOPTRUNGTAM", Storage="_CHITIETLOPTRUNGTAMs", ThisKey="MAGS", OtherKey="MAGS")]
		public EntitySet<CHITIETLOPTRUNGTAM> CHITIETLOPTRUNGTAMs
		{
			get
			{
				return this._CHITIETLOPTRUNGTAMs;
			}
			set
			{
				this._CHITIETLOPTRUNGTAMs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GIASU_DANHSACHHEN", Storage="_DANHSACHHENs", ThisKey="MAGS", OtherKey="MAGS")]
		public EntitySet<DANHSACHHEN> DANHSACHHENs
		{
			get
			{
				return this._DANHSACHHENs;
			}
			set
			{
				this._DANHSACHHENs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHITIETGs(CHITIETG entity)
		{
			this.SendPropertyChanging();
			entity.GIASU = this;
		}
		
		private void detach_CHITIETGs(CHITIETG entity)
		{
			this.SendPropertyChanging();
			entity.GIASU = null;
		}
		
		private void attach_CHITIETLOPTRUNGTAMs(CHITIETLOPTRUNGTAM entity)
		{
			this.SendPropertyChanging();
			entity.GIASU = this;
		}
		
		private void detach_CHITIETLOPTRUNGTAMs(CHITIETLOPTRUNGTAM entity)
		{
			this.SendPropertyChanging();
			entity.GIASU = null;
		}
		
		private void attach_DANHSACHHENs(DANHSACHHEN entity)
		{
			this.SendPropertyChanging();
			entity.GIASU = this;
		}
		
		private void detach_DANHSACHHENs(DANHSACHHEN entity)
		{
			this.SendPropertyChanging();
			entity.GIASU = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HOCVIEN")]
	public partial class HOCVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MAHV;
		
		private string _TENHV;
		
		private System.Nullable<System.DateTime> _NGAYSINH;
		
		private string _TRUONG;
		
		private string _LOP;
		
		private string _DIACHI;
		
		private string _DIENTHOAI;
		
		private string _HOCLUC;
		
		private string _CCCD;
		
		private string _MONDANGKY;
		
		private string _GHICHU;
		
		private System.Nullable<int> _MAPH;
		
		private EntitySet<DANHSACHHEN> _DANHSACHHENs;
		
		private EntitySet<LOPTRUNGTAM> _LOPTRUNGTAMs;
		
		private EntityRef<PHUHUYNH> _PHUHUYNH;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAHVChanging(int value);
    partial void OnMAHVChanged();
    partial void OnTENHVChanging(string value);
    partial void OnTENHVChanged();
    partial void OnNGAYSINHChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYSINHChanged();
    partial void OnTRUONGChanging(string value);
    partial void OnTRUONGChanged();
    partial void OnLOPChanging(string value);
    partial void OnLOPChanged();
    partial void OnDIACHIChanging(string value);
    partial void OnDIACHIChanged();
    partial void OnDIENTHOAIChanging(string value);
    partial void OnDIENTHOAIChanged();
    partial void OnHOCLUCChanging(string value);
    partial void OnHOCLUCChanged();
    partial void OnCCCDChanging(string value);
    partial void OnCCCDChanged();
    partial void OnMONDANGKYChanging(string value);
    partial void OnMONDANGKYChanged();
    partial void OnGHICHUChanging(string value);
    partial void OnGHICHUChanged();
    partial void OnMAPHChanging(System.Nullable<int> value);
    partial void OnMAPHChanged();
    #endregion
		
		public HOCVIEN()
		{
			this._DANHSACHHENs = new EntitySet<DANHSACHHEN>(new Action<DANHSACHHEN>(this.attach_DANHSACHHENs), new Action<DANHSACHHEN>(this.detach_DANHSACHHENs));
			this._LOPTRUNGTAMs = new EntitySet<LOPTRUNGTAM>(new Action<LOPTRUNGTAM>(this.attach_LOPTRUNGTAMs), new Action<LOPTRUNGTAM>(this.detach_LOPTRUNGTAMs));
			this._PHUHUYNH = default(EntityRef<PHUHUYNH>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAHV", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MAHV
		{
			get
			{
				return this._MAHV;
			}
			set
			{
				if ((this._MAHV != value))
				{
					this.OnMAHVChanging(value);
					this.SendPropertyChanging();
					this._MAHV = value;
					this.SendPropertyChanged("MAHV");
					this.OnMAHVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENHV", DbType="NVarChar(100)")]
		public string TENHV
		{
			get
			{
				return this._TENHV;
			}
			set
			{
				if ((this._TENHV != value))
				{
					this.OnTENHVChanging(value);
					this.SendPropertyChanging();
					this._TENHV = value;
					this.SendPropertyChanged("TENHV");
					this.OnTENHVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYSINH", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYSINH
		{
			get
			{
				return this._NGAYSINH;
			}
			set
			{
				if ((this._NGAYSINH != value))
				{
					this.OnNGAYSINHChanging(value);
					this.SendPropertyChanging();
					this._NGAYSINH = value;
					this.SendPropertyChanged("NGAYSINH");
					this.OnNGAYSINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRUONG", DbType="NVarChar(100)")]
		public string TRUONG
		{
			get
			{
				return this._TRUONG;
			}
			set
			{
				if ((this._TRUONG != value))
				{
					this.OnTRUONGChanging(value);
					this.SendPropertyChanging();
					this._TRUONG = value;
					this.SendPropertyChanged("TRUONG");
					this.OnTRUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOP", DbType="NVarChar(50)")]
		public string LOP
		{
			get
			{
				return this._LOP;
			}
			set
			{
				if ((this._LOP != value))
				{
					this.OnLOPChanging(value);
					this.SendPropertyChanging();
					this._LOP = value;
					this.SendPropertyChanged("LOP");
					this.OnLOPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHI", DbType="NVarChar(100)")]
		public string DIACHI
		{
			get
			{
				return this._DIACHI;
			}
			set
			{
				if ((this._DIACHI != value))
				{
					this.OnDIACHIChanging(value);
					this.SendPropertyChanging();
					this._DIACHI = value;
					this.SendPropertyChanged("DIACHI");
					this.OnDIACHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIENTHOAI", DbType="Char(10)")]
		public string DIENTHOAI
		{
			get
			{
				return this._DIENTHOAI;
			}
			set
			{
				if ((this._DIENTHOAI != value))
				{
					this.OnDIENTHOAIChanging(value);
					this.SendPropertyChanging();
					this._DIENTHOAI = value;
					this.SendPropertyChanged("DIENTHOAI");
					this.OnDIENTHOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOCLUC", DbType="NVarChar(100)")]
		public string HOCLUC
		{
			get
			{
				return this._HOCLUC;
			}
			set
			{
				if ((this._HOCLUC != value))
				{
					this.OnHOCLUCChanging(value);
					this.SendPropertyChanging();
					this._HOCLUC = value;
					this.SendPropertyChanged("HOCLUC");
					this.OnHOCLUCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CCCD", DbType="Char(20)")]
		public string CCCD
		{
			get
			{
				return this._CCCD;
			}
			set
			{
				if ((this._CCCD != value))
				{
					this.OnCCCDChanging(value);
					this.SendPropertyChanging();
					this._CCCD = value;
					this.SendPropertyChanged("CCCD");
					this.OnCCCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MONDANGKY", DbType="Char(10)")]
		public string MONDANGKY
		{
			get
			{
				return this._MONDANGKY;
			}
			set
			{
				if ((this._MONDANGKY != value))
				{
					this.OnMONDANGKYChanging(value);
					this.SendPropertyChanging();
					this._MONDANGKY = value;
					this.SendPropertyChanged("MONDANGKY");
					this.OnMONDANGKYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GHICHU", DbType="NVarChar(1000)")]
		public string GHICHU
		{
			get
			{
				return this._GHICHU;
			}
			set
			{
				if ((this._GHICHU != value))
				{
					this.OnGHICHUChanging(value);
					this.SendPropertyChanging();
					this._GHICHU = value;
					this.SendPropertyChanged("GHICHU");
					this.OnGHICHUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAPH", DbType="Int")]
		public System.Nullable<int> MAPH
		{
			get
			{
				return this._MAPH;
			}
			set
			{
				if ((this._MAPH != value))
				{
					if (this._PHUHUYNH.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAPHChanging(value);
					this.SendPropertyChanging();
					this._MAPH = value;
					this.SendPropertyChanged("MAPH");
					this.OnMAPHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOCVIEN_DANHSACHHEN", Storage="_DANHSACHHENs", ThisKey="MAHV", OtherKey="MAHV")]
		public EntitySet<DANHSACHHEN> DANHSACHHENs
		{
			get
			{
				return this._DANHSACHHENs;
			}
			set
			{
				this._DANHSACHHENs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOCVIEN_LOPTRUNGTAM", Storage="_LOPTRUNGTAMs", ThisKey="MAHV", OtherKey="MAHV")]
		public EntitySet<LOPTRUNGTAM> LOPTRUNGTAMs
		{
			get
			{
				return this._LOPTRUNGTAMs;
			}
			set
			{
				this._LOPTRUNGTAMs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHUHUYNH_HOCVIEN", Storage="_PHUHUYNH", ThisKey="MAPH", OtherKey="MAPH", IsForeignKey=true)]
		public PHUHUYNH PHUHUYNH
		{
			get
			{
				return this._PHUHUYNH.Entity;
			}
			set
			{
				PHUHUYNH previousValue = this._PHUHUYNH.Entity;
				if (((previousValue != value) 
							|| (this._PHUHUYNH.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PHUHUYNH.Entity = null;
						previousValue.HOCVIENs.Remove(this);
					}
					this._PHUHUYNH.Entity = value;
					if ((value != null))
					{
						value.HOCVIENs.Add(this);
						this._MAPH = value.MAPH;
					}
					else
					{
						this._MAPH = default(Nullable<int>);
					}
					this.SendPropertyChanged("PHUHUYNH");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DANHSACHHENs(DANHSACHHEN entity)
		{
			this.SendPropertyChanging();
			entity.HOCVIEN = this;
		}
		
		private void detach_DANHSACHHENs(DANHSACHHEN entity)
		{
			this.SendPropertyChanging();
			entity.HOCVIEN = null;
		}
		
		private void attach_LOPTRUNGTAMs(LOPTRUNGTAM entity)
		{
			this.SendPropertyChanging();
			entity.HOCVIEN = this;
		}
		
		private void detach_LOPTRUNGTAMs(LOPTRUNGTAM entity)
		{
			this.SendPropertyChanging();
			entity.HOCVIEN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KHUVUC")]
	public partial class KHUVUC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MAKV;
		
		private string _TENKV;
		
		private EntitySet<CHITIETG> _CHITIETGs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAKVChanging(int value);
    partial void OnMAKVChanged();
    partial void OnTENKVChanging(string value);
    partial void OnTENKVChanged();
    #endregion
		
		public KHUVUC()
		{
			this._CHITIETGs = new EntitySet<CHITIETG>(new Action<CHITIETG>(this.attach_CHITIETGs), new Action<CHITIETG>(this.detach_CHITIETGs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAKV", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MAKV
		{
			get
			{
				return this._MAKV;
			}
			set
			{
				if ((this._MAKV != value))
				{
					this.OnMAKVChanging(value);
					this.SendPropertyChanging();
					this._MAKV = value;
					this.SendPropertyChanged("MAKV");
					this.OnMAKVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENKV", DbType="NVarChar(100)")]
		public string TENKV
		{
			get
			{
				return this._TENKV;
			}
			set
			{
				if ((this._TENKV != value))
				{
					this.OnTENKVChanging(value);
					this.SendPropertyChanging();
					this._TENKV = value;
					this.SendPropertyChanged("TENKV");
					this.OnTENKVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHUVUC_CHITIETG", Storage="_CHITIETGs", ThisKey="MAKV", OtherKey="MAKV")]
		public EntitySet<CHITIETG> CHITIETGs
		{
			get
			{
				return this._CHITIETGs;
			}
			set
			{
				this._CHITIETGs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHITIETGs(CHITIETG entity)
		{
			this.SendPropertyChanging();
			entity.KHUVUC = this;
		}
		
		private void detach_CHITIETGs(CHITIETG entity)
		{
			this.SendPropertyChanging();
			entity.KHUVUC = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOP")]
	public partial class LOP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MALOP;
		
		private string _TENLOP;
		
		private EntitySet<CHITIETG> _CHITIETGs;
		
		private EntitySet<LOPTRUNGTAM> _LOPTRUNGTAMs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMALOPChanging(int value);
    partial void OnMALOPChanged();
    partial void OnTENLOPChanging(string value);
    partial void OnTENLOPChanged();
    #endregion
		
		public LOP()
		{
			this._CHITIETGs = new EntitySet<CHITIETG>(new Action<CHITIETG>(this.attach_CHITIETGs), new Action<CHITIETG>(this.detach_CHITIETGs));
			this._LOPTRUNGTAMs = new EntitySet<LOPTRUNGTAM>(new Action<LOPTRUNGTAM>(this.attach_LOPTRUNGTAMs), new Action<LOPTRUNGTAM>(this.detach_LOPTRUNGTAMs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MALOP", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MALOP
		{
			get
			{
				return this._MALOP;
			}
			set
			{
				if ((this._MALOP != value))
				{
					this.OnMALOPChanging(value);
					this.SendPropertyChanging();
					this._MALOP = value;
					this.SendPropertyChanged("MALOP");
					this.OnMALOPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENLOP", DbType="NVarChar(100)")]
		public string TENLOP
		{
			get
			{
				return this._TENLOP;
			}
			set
			{
				if ((this._TENLOP != value))
				{
					this.OnTENLOPChanging(value);
					this.SendPropertyChanging();
					this._TENLOP = value;
					this.SendPropertyChanged("TENLOP");
					this.OnTENLOPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOP_CHITIETG", Storage="_CHITIETGs", ThisKey="MALOP", OtherKey="MALOP")]
		public EntitySet<CHITIETG> CHITIETGs
		{
			get
			{
				return this._CHITIETGs;
			}
			set
			{
				this._CHITIETGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOP_LOPTRUNGTAM", Storage="_LOPTRUNGTAMs", ThisKey="MALOP", OtherKey="MALOP")]
		public EntitySet<LOPTRUNGTAM> LOPTRUNGTAMs
		{
			get
			{
				return this._LOPTRUNGTAMs;
			}
			set
			{
				this._LOPTRUNGTAMs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHITIETGs(CHITIETG entity)
		{
			this.SendPropertyChanging();
			entity.LOP = this;
		}
		
		private void detach_CHITIETGs(CHITIETG entity)
		{
			this.SendPropertyChanging();
			entity.LOP = null;
		}
		
		private void attach_LOPTRUNGTAMs(LOPTRUNGTAM entity)
		{
			this.SendPropertyChanging();
			entity.LOP = this;
		}
		
		private void detach_LOPTRUNGTAMs(LOPTRUNGTAM entity)
		{
			this.SendPropertyChanging();
			entity.LOP = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOPTRUNGTAM")]
	public partial class LOPTRUNGTAM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MALOPTT;
		
		private int _MAHV;
		
		private int _MAPH;
		
		private int _MALOP;
		
		private int _MAMON;
		
		private int _MATG;
		
		private int _SOLUONGHV;
		
		private int _SOBUOI;
		
		private string _YEUCAUKHAC;
		
		private System.Nullable<bool> _TRANGTHAI;
		
		private EntitySet<CHITIETLOPTRUNGTAM> _CHITIETLOPTRUNGTAMs;
		
		private EntityRef<HOCVIEN> _HOCVIEN;
		
		private EntityRef<LOP> _LOP;
		
		private EntityRef<THOIGIAN> _THOIGIAN;
		
		private EntityRef<MON> _MON;
		
		private EntityRef<PHUHUYNH> _PHUHUYNH;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMALOPTTChanging(int value);
    partial void OnMALOPTTChanged();
    partial void OnMAHVChanging(int value);
    partial void OnMAHVChanged();
    partial void OnMAPHChanging(int value);
    partial void OnMAPHChanged();
    partial void OnMALOPChanging(int value);
    partial void OnMALOPChanged();
    partial void OnMAMONChanging(int value);
    partial void OnMAMONChanged();
    partial void OnMATGChanging(int value);
    partial void OnMATGChanged();
    partial void OnSOLUONGHVChanging(int value);
    partial void OnSOLUONGHVChanged();
    partial void OnSOBUOIChanging(int value);
    partial void OnSOBUOIChanged();
    partial void OnYEUCAUKHACChanging(string value);
    partial void OnYEUCAUKHACChanged();
    partial void OnTRANGTHAIChanging(System.Nullable<bool> value);
    partial void OnTRANGTHAIChanged();
    #endregion
		
		public LOPTRUNGTAM()
		{
			this._CHITIETLOPTRUNGTAMs = new EntitySet<CHITIETLOPTRUNGTAM>(new Action<CHITIETLOPTRUNGTAM>(this.attach_CHITIETLOPTRUNGTAMs), new Action<CHITIETLOPTRUNGTAM>(this.detach_CHITIETLOPTRUNGTAMs));
			this._HOCVIEN = default(EntityRef<HOCVIEN>);
			this._LOP = default(EntityRef<LOP>);
			this._THOIGIAN = default(EntityRef<THOIGIAN>);
			this._MON = default(EntityRef<MON>);
			this._PHUHUYNH = default(EntityRef<PHUHUYNH>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MALOPTT", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MALOPTT
		{
			get
			{
				return this._MALOPTT;
			}
			set
			{
				if ((this._MALOPTT != value))
				{
					this.OnMALOPTTChanging(value);
					this.SendPropertyChanging();
					this._MALOPTT = value;
					this.SendPropertyChanged("MALOPTT");
					this.OnMALOPTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAHV", DbType="Int NOT NULL")]
		public int MAHV
		{
			get
			{
				return this._MAHV;
			}
			set
			{
				if ((this._MAHV != value))
				{
					if (this._HOCVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAHVChanging(value);
					this.SendPropertyChanging();
					this._MAHV = value;
					this.SendPropertyChanged("MAHV");
					this.OnMAHVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAPH", DbType="Int NOT NULL")]
		public int MAPH
		{
			get
			{
				return this._MAPH;
			}
			set
			{
				if ((this._MAPH != value))
				{
					if (this._PHUHUYNH.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAPHChanging(value);
					this.SendPropertyChanging();
					this._MAPH = value;
					this.SendPropertyChanged("MAPH");
					this.OnMAPHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MALOP", DbType="Int NOT NULL")]
		public int MALOP
		{
			get
			{
				return this._MALOP;
			}
			set
			{
				if ((this._MALOP != value))
				{
					if (this._LOP.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMALOPChanging(value);
					this.SendPropertyChanging();
					this._MALOP = value;
					this.SendPropertyChanged("MALOP");
					this.OnMALOPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAMON", DbType="Int NOT NULL")]
		public int MAMON
		{
			get
			{
				return this._MAMON;
			}
			set
			{
				if ((this._MAMON != value))
				{
					if (this._MON.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAMONChanging(value);
					this.SendPropertyChanging();
					this._MAMON = value;
					this.SendPropertyChanged("MAMON");
					this.OnMAMONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATG", DbType="Int NOT NULL")]
		public int MATG
		{
			get
			{
				return this._MATG;
			}
			set
			{
				if ((this._MATG != value))
				{
					if (this._THOIGIAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMATGChanging(value);
					this.SendPropertyChanging();
					this._MATG = value;
					this.SendPropertyChanged("MATG");
					this.OnMATGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOLUONGHV", DbType="Int NOT NULL")]
		public int SOLUONGHV
		{
			get
			{
				return this._SOLUONGHV;
			}
			set
			{
				if ((this._SOLUONGHV != value))
				{
					this.OnSOLUONGHVChanging(value);
					this.SendPropertyChanging();
					this._SOLUONGHV = value;
					this.SendPropertyChanged("SOLUONGHV");
					this.OnSOLUONGHVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOBUOI", DbType="Int NOT NULL")]
		public int SOBUOI
		{
			get
			{
				return this._SOBUOI;
			}
			set
			{
				if ((this._SOBUOI != value))
				{
					this.OnSOBUOIChanging(value);
					this.SendPropertyChanging();
					this._SOBUOI = value;
					this.SendPropertyChanged("SOBUOI");
					this.OnSOBUOIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YEUCAUKHAC", DbType="NVarChar(1000)")]
		public string YEUCAUKHAC
		{
			get
			{
				return this._YEUCAUKHAC;
			}
			set
			{
				if ((this._YEUCAUKHAC != value))
				{
					this.OnYEUCAUKHACChanging(value);
					this.SendPropertyChanging();
					this._YEUCAUKHAC = value;
					this.SendPropertyChanged("YEUCAUKHAC");
					this.OnYEUCAUKHACChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRANGTHAI", DbType="Bit")]
		public System.Nullable<bool> TRANGTHAI
		{
			get
			{
				return this._TRANGTHAI;
			}
			set
			{
				if ((this._TRANGTHAI != value))
				{
					this.OnTRANGTHAIChanging(value);
					this.SendPropertyChanging();
					this._TRANGTHAI = value;
					this.SendPropertyChanged("TRANGTHAI");
					this.OnTRANGTHAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOPTRUNGTAM_CHITIETLOPTRUNGTAM", Storage="_CHITIETLOPTRUNGTAMs", ThisKey="MALOPTT", OtherKey="MALOPTT")]
		public EntitySet<CHITIETLOPTRUNGTAM> CHITIETLOPTRUNGTAMs
		{
			get
			{
				return this._CHITIETLOPTRUNGTAMs;
			}
			set
			{
				this._CHITIETLOPTRUNGTAMs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOCVIEN_LOPTRUNGTAM", Storage="_HOCVIEN", ThisKey="MAHV", OtherKey="MAHV", IsForeignKey=true)]
		public HOCVIEN HOCVIEN
		{
			get
			{
				return this._HOCVIEN.Entity;
			}
			set
			{
				HOCVIEN previousValue = this._HOCVIEN.Entity;
				if (((previousValue != value) 
							|| (this._HOCVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HOCVIEN.Entity = null;
						previousValue.LOPTRUNGTAMs.Remove(this);
					}
					this._HOCVIEN.Entity = value;
					if ((value != null))
					{
						value.LOPTRUNGTAMs.Add(this);
						this._MAHV = value.MAHV;
					}
					else
					{
						this._MAHV = default(int);
					}
					this.SendPropertyChanged("HOCVIEN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOP_LOPTRUNGTAM", Storage="_LOP", ThisKey="MALOP", OtherKey="MALOP", IsForeignKey=true)]
		public LOP LOP
		{
			get
			{
				return this._LOP.Entity;
			}
			set
			{
				LOP previousValue = this._LOP.Entity;
				if (((previousValue != value) 
							|| (this._LOP.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOP.Entity = null;
						previousValue.LOPTRUNGTAMs.Remove(this);
					}
					this._LOP.Entity = value;
					if ((value != null))
					{
						value.LOPTRUNGTAMs.Add(this);
						this._MALOP = value.MALOP;
					}
					else
					{
						this._MALOP = default(int);
					}
					this.SendPropertyChanged("LOP");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THOIGIAN_LOPTRUNGTAM", Storage="_THOIGIAN", ThisKey="MATG", OtherKey="MATG", IsForeignKey=true)]
		public THOIGIAN THOIGIAN
		{
			get
			{
				return this._THOIGIAN.Entity;
			}
			set
			{
				THOIGIAN previousValue = this._THOIGIAN.Entity;
				if (((previousValue != value) 
							|| (this._THOIGIAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._THOIGIAN.Entity = null;
						previousValue.LOPTRUNGTAMs.Remove(this);
					}
					this._THOIGIAN.Entity = value;
					if ((value != null))
					{
						value.LOPTRUNGTAMs.Add(this);
						this._MATG = value.MATG;
					}
					else
					{
						this._MATG = default(int);
					}
					this.SendPropertyChanged("THOIGIAN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MON_LOPTRUNGTAM", Storage="_MON", ThisKey="MAMON", OtherKey="MAMON", IsForeignKey=true)]
		public MON MON
		{
			get
			{
				return this._MON.Entity;
			}
			set
			{
				MON previousValue = this._MON.Entity;
				if (((previousValue != value) 
							|| (this._MON.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MON.Entity = null;
						previousValue.LOPTRUNGTAMs.Remove(this);
					}
					this._MON.Entity = value;
					if ((value != null))
					{
						value.LOPTRUNGTAMs.Add(this);
						this._MAMON = value.MAMON;
					}
					else
					{
						this._MAMON = default(int);
					}
					this.SendPropertyChanged("MON");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHUHUYNH_LOPTRUNGTAM", Storage="_PHUHUYNH", ThisKey="MAPH", OtherKey="MAPH", IsForeignKey=true)]
		public PHUHUYNH PHUHUYNH
		{
			get
			{
				return this._PHUHUYNH.Entity;
			}
			set
			{
				PHUHUYNH previousValue = this._PHUHUYNH.Entity;
				if (((previousValue != value) 
							|| (this._PHUHUYNH.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PHUHUYNH.Entity = null;
						previousValue.LOPTRUNGTAMs.Remove(this);
					}
					this._PHUHUYNH.Entity = value;
					if ((value != null))
					{
						value.LOPTRUNGTAMs.Add(this);
						this._MAPH = value.MAPH;
					}
					else
					{
						this._MAPH = default(int);
					}
					this.SendPropertyChanged("PHUHUYNH");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHITIETLOPTRUNGTAMs(CHITIETLOPTRUNGTAM entity)
		{
			this.SendPropertyChanging();
			entity.LOPTRUNGTAM = this;
		}
		
		private void detach_CHITIETLOPTRUNGTAMs(CHITIETLOPTRUNGTAM entity)
		{
			this.SendPropertyChanging();
			entity.LOPTRUNGTAM = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MON")]
	public partial class MON : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MAMON;
		
		private string _TENMON;
		
		private EntitySet<CHITIETG> _CHITIETGs;
		
		private EntitySet<LOPTRUNGTAM> _LOPTRUNGTAMs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAMONChanging(int value);
    partial void OnMAMONChanged();
    partial void OnTENMONChanging(string value);
    partial void OnTENMONChanged();
    #endregion
		
		public MON()
		{
			this._CHITIETGs = new EntitySet<CHITIETG>(new Action<CHITIETG>(this.attach_CHITIETGs), new Action<CHITIETG>(this.detach_CHITIETGs));
			this._LOPTRUNGTAMs = new EntitySet<LOPTRUNGTAM>(new Action<LOPTRUNGTAM>(this.attach_LOPTRUNGTAMs), new Action<LOPTRUNGTAM>(this.detach_LOPTRUNGTAMs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAMON", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MAMON
		{
			get
			{
				return this._MAMON;
			}
			set
			{
				if ((this._MAMON != value))
				{
					this.OnMAMONChanging(value);
					this.SendPropertyChanging();
					this._MAMON = value;
					this.SendPropertyChanged("MAMON");
					this.OnMAMONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENMON", DbType="NVarChar(100)")]
		public string TENMON
		{
			get
			{
				return this._TENMON;
			}
			set
			{
				if ((this._TENMON != value))
				{
					this.OnTENMONChanging(value);
					this.SendPropertyChanging();
					this._TENMON = value;
					this.SendPropertyChanged("TENMON");
					this.OnTENMONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MON_CHITIETG", Storage="_CHITIETGs", ThisKey="MAMON", OtherKey="MAMON")]
		public EntitySet<CHITIETG> CHITIETGs
		{
			get
			{
				return this._CHITIETGs;
			}
			set
			{
				this._CHITIETGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MON_LOPTRUNGTAM", Storage="_LOPTRUNGTAMs", ThisKey="MAMON", OtherKey="MAMON")]
		public EntitySet<LOPTRUNGTAM> LOPTRUNGTAMs
		{
			get
			{
				return this._LOPTRUNGTAMs;
			}
			set
			{
				this._LOPTRUNGTAMs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHITIETGs(CHITIETG entity)
		{
			this.SendPropertyChanging();
			entity.MON = this;
		}
		
		private void detach_CHITIETGs(CHITIETG entity)
		{
			this.SendPropertyChanging();
			entity.MON = null;
		}
		
		private void attach_LOPTRUNGTAMs(LOPTRUNGTAM entity)
		{
			this.SendPropertyChanging();
			entity.MON = this;
		}
		
		private void detach_LOPTRUNGTAMs(LOPTRUNGTAM entity)
		{
			this.SendPropertyChanging();
			entity.MON = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHANVIEN")]
	public partial class NHANVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MANV;
		
		private string _TENNV;
		
		private string _DIACHI;
		
		private string _SDT;
		
		private string _CHUCVU;
		
		private string _MATKHAU;
		
		private EntitySet<CHITIETLOPTRUNGTAM> _CHITIETLOPTRUNGTAMs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMANVChanging(int value);
    partial void OnMANVChanged();
    partial void OnTENNVChanging(string value);
    partial void OnTENNVChanged();
    partial void OnDIACHIChanging(string value);
    partial void OnDIACHIChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnCHUCVUChanging(string value);
    partial void OnCHUCVUChanged();
    partial void OnMATKHAUChanging(string value);
    partial void OnMATKHAUChanged();
    #endregion
		
		public NHANVIEN()
		{
			this._CHITIETLOPTRUNGTAMs = new EntitySet<CHITIETLOPTRUNGTAM>(new Action<CHITIETLOPTRUNGTAM>(this.attach_CHITIETLOPTRUNGTAMs), new Action<CHITIETLOPTRUNGTAM>(this.detach_CHITIETLOPTRUNGTAMs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANV", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MANV
		{
			get
			{
				return this._MANV;
			}
			set
			{
				if ((this._MANV != value))
				{
					this.OnMANVChanging(value);
					this.SendPropertyChanging();
					this._MANV = value;
					this.SendPropertyChanged("MANV");
					this.OnMANVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENNV", DbType="NVarChar(100)")]
		public string TENNV
		{
			get
			{
				return this._TENNV;
			}
			set
			{
				if ((this._TENNV != value))
				{
					this.OnTENNVChanging(value);
					this.SendPropertyChanging();
					this._TENNV = value;
					this.SendPropertyChanged("TENNV");
					this.OnTENNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHI", DbType="NVarChar(100)")]
		public string DIACHI
		{
			get
			{
				return this._DIACHI;
			}
			set
			{
				if ((this._DIACHI != value))
				{
					this.OnDIACHIChanging(value);
					this.SendPropertyChanging();
					this._DIACHI = value;
					this.SendPropertyChanged("DIACHI");
					this.OnDIACHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="Char(10)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHUCVU", DbType="Char(20)")]
		public string CHUCVU
		{
			get
			{
				return this._CHUCVU;
			}
			set
			{
				if ((this._CHUCVU != value))
				{
					this.OnCHUCVUChanging(value);
					this.SendPropertyChanging();
					this._CHUCVU = value;
					this.SendPropertyChanged("CHUCVU");
					this.OnCHUCVUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATKHAU", DbType="Char(10)")]
		public string MATKHAU
		{
			get
			{
				return this._MATKHAU;
			}
			set
			{
				if ((this._MATKHAU != value))
				{
					this.OnMATKHAUChanging(value);
					this.SendPropertyChanging();
					this._MATKHAU = value;
					this.SendPropertyChanged("MATKHAU");
					this.OnMATKHAUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_CHITIETLOPTRUNGTAM", Storage="_CHITIETLOPTRUNGTAMs", ThisKey="MANV", OtherKey="MANV")]
		public EntitySet<CHITIETLOPTRUNGTAM> CHITIETLOPTRUNGTAMs
		{
			get
			{
				return this._CHITIETLOPTRUNGTAMs;
			}
			set
			{
				this._CHITIETLOPTRUNGTAMs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHITIETLOPTRUNGTAMs(CHITIETLOPTRUNGTAM entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = this;
		}
		
		private void detach_CHITIETLOPTRUNGTAMs(CHITIETLOPTRUNGTAM entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHUHUYNH")]
	public partial class PHUHUYNH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MAPH;
		
		private string _TENPH;
		
		private string _DIACHI;
		
		private string _DIENTHOAI;
		
		private EntitySet<HOCVIEN> _HOCVIENs;
		
		private EntitySet<LOPTRUNGTAM> _LOPTRUNGTAMs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAPHChanging(int value);
    partial void OnMAPHChanged();
    partial void OnTENPHChanging(string value);
    partial void OnTENPHChanged();
    partial void OnDIACHIChanging(string value);
    partial void OnDIACHIChanged();
    partial void OnDIENTHOAIChanging(string value);
    partial void OnDIENTHOAIChanged();
    #endregion
		
		public PHUHUYNH()
		{
			this._HOCVIENs = new EntitySet<HOCVIEN>(new Action<HOCVIEN>(this.attach_HOCVIENs), new Action<HOCVIEN>(this.detach_HOCVIENs));
			this._LOPTRUNGTAMs = new EntitySet<LOPTRUNGTAM>(new Action<LOPTRUNGTAM>(this.attach_LOPTRUNGTAMs), new Action<LOPTRUNGTAM>(this.detach_LOPTRUNGTAMs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAPH", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MAPH
		{
			get
			{
				return this._MAPH;
			}
			set
			{
				if ((this._MAPH != value))
				{
					this.OnMAPHChanging(value);
					this.SendPropertyChanging();
					this._MAPH = value;
					this.SendPropertyChanged("MAPH");
					this.OnMAPHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENPH", DbType="NVarChar(100)")]
		public string TENPH
		{
			get
			{
				return this._TENPH;
			}
			set
			{
				if ((this._TENPH != value))
				{
					this.OnTENPHChanging(value);
					this.SendPropertyChanging();
					this._TENPH = value;
					this.SendPropertyChanged("TENPH");
					this.OnTENPHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHI", DbType="NVarChar(100)")]
		public string DIACHI
		{
			get
			{
				return this._DIACHI;
			}
			set
			{
				if ((this._DIACHI != value))
				{
					this.OnDIACHIChanging(value);
					this.SendPropertyChanging();
					this._DIACHI = value;
					this.SendPropertyChanged("DIACHI");
					this.OnDIACHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIENTHOAI", DbType="Char(10)")]
		public string DIENTHOAI
		{
			get
			{
				return this._DIENTHOAI;
			}
			set
			{
				if ((this._DIENTHOAI != value))
				{
					this.OnDIENTHOAIChanging(value);
					this.SendPropertyChanging();
					this._DIENTHOAI = value;
					this.SendPropertyChanged("DIENTHOAI");
					this.OnDIENTHOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHUHUYNH_HOCVIEN", Storage="_HOCVIENs", ThisKey="MAPH", OtherKey="MAPH")]
		public EntitySet<HOCVIEN> HOCVIENs
		{
			get
			{
				return this._HOCVIENs;
			}
			set
			{
				this._HOCVIENs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHUHUYNH_LOPTRUNGTAM", Storage="_LOPTRUNGTAMs", ThisKey="MAPH", OtherKey="MAPH")]
		public EntitySet<LOPTRUNGTAM> LOPTRUNGTAMs
		{
			get
			{
				return this._LOPTRUNGTAMs;
			}
			set
			{
				this._LOPTRUNGTAMs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HOCVIENs(HOCVIEN entity)
		{
			this.SendPropertyChanging();
			entity.PHUHUYNH = this;
		}
		
		private void detach_HOCVIENs(HOCVIEN entity)
		{
			this.SendPropertyChanging();
			entity.PHUHUYNH = null;
		}
		
		private void attach_LOPTRUNGTAMs(LOPTRUNGTAM entity)
		{
			this.SendPropertyChanging();
			entity.PHUHUYNH = this;
		}
		
		private void detach_LOPTRUNGTAMs(LOPTRUNGTAM entity)
		{
			this.SendPropertyChanging();
			entity.PHUHUYNH = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TAIKHOAN")]
	public partial class TAIKHOAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Users;
		
		private string _Pass;
		
		private string _HoTen;
		
		private string _Quyen;
		
		private string _ChucVu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUsersChanging(string value);
    partial void OnUsersChanged();
    partial void OnPassChanging(string value);
    partial void OnPassChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnQuyenChanging(string value);
    partial void OnQuyenChanged();
    partial void OnChucVuChanging(string value);
    partial void OnChucVuChanged();
    #endregion
		
		public TAIKHOAN()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Users", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Users
		{
			get
			{
				return this._Users;
			}
			set
			{
				if ((this._Users != value))
				{
					this.OnUsersChanging(value);
					this.SendPropertyChanging();
					this._Users = value;
					this.SendPropertyChanged("Users");
					this.OnUsersChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pass", DbType="NVarChar(50)")]
		public string Pass
		{
			get
			{
				return this._Pass;
			}
			set
			{
				if ((this._Pass != value))
				{
					this.OnPassChanging(value);
					this.SendPropertyChanging();
					this._Pass = value;
					this.SendPropertyChanged("Pass");
					this.OnPassChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(50)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quyen", DbType="NVarChar(20)")]
		public string Quyen
		{
			get
			{
				return this._Quyen;
			}
			set
			{
				if ((this._Quyen != value))
				{
					this.OnQuyenChanging(value);
					this.SendPropertyChanging();
					this._Quyen = value;
					this.SendPropertyChanged("Quyen");
					this.OnQuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChucVu", DbType="NVarChar(50)")]
		public string ChucVu
		{
			get
			{
				return this._ChucVu;
			}
			set
			{
				if ((this._ChucVu != value))
				{
					this.OnChucVuChanging(value);
					this.SendPropertyChanging();
					this._ChucVu = value;
					this.SendPropertyChanged("ChucVu");
					this.OnChucVuChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
